CREATE TABLE seat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_number VARCHAR(255),
    flight_id BIGINT,
    tenant_id VARCHAR(255),
    booked BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_seat_flight FOREIGN KEY (flight_id) REFERENCES flight(id)
);
