CREATE TABLE support_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id VARCHAR(255),
    subject VARCHAR(255),
    message TEXT,
    email VARCHAR(255),
    type VARCHAR(255),
    status VARCHAR(255),
    created_at TIMESTAMP,
    tenant_id VARCHAR(255),
    flight_id BIGINT,
    CONSTRAINT fk_support_flight FOREIGN KEY (flight_id) REFERENCES flight(id)
);
