CREATE TABLE terminals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    airport_id BIGINT NOT NULL,
    tenant_id VARCHAR(255) NOT NULL,
    CONSTRAINT fk_terminal_airport FOREIGN KEY (airport_id) REFERENCES airport(id)
);
