CREATE TABLE trending_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    season VARCHAR(255),
    image_url VARCHAR(255),
    tenant_id VARCHAR(255)
);
